--- 
clone: 
  depth: 1
kind: pipeline
name: silont-project
steps: 
  - 
    commands:
      - "curl -OsSL https://github.com/azrim/script/raw/master/kernel/drone.sh"
      - "bash drone.sh"
    image: azrim89/hitagi:fedora
    name: azrim
    trigger: 
      branch: 
        - new
        
